version: '3'
services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: seller-finding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"

volumes:
  postgres: