// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SellersColumns holds the columns for the "sellers" table.
	SellersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "tel", Type: field.TypeString, Nullable: true},
		{Name: "prefecture", Type: field.TypeString, Nullable: true},
		{Name: "address", Type: field.TypeString, Nullable: true},
		{Name: "latitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "longitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "opened_at", Type: field.TypeTime, Nullable: true},
		{Name: "exported", Type: field.TypeBool},
		{Name: "exported_at", Type: field.TypeTime, Nullable: true},
		{Name: "disabled", Type: field.TypeBool},
	}
	// SellersTable holds the schema information for the "sellers" table.
	SellersTable = &schema.Table{
		Name:       "sellers",
		Columns:    SellersColumns,
		PrimaryKey: []*schema.Column{SellersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "seller_prefecture_opened_at",
				Unique:  false,
				Columns: []*schema.Column{SellersColumns[7], SellersColumns[11]},
			},
		},
	}
	// WebsitesColumns holds the columns for the "websites" table.
	WebsitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "url_template", Type: field.TypeString, Unique: true},
		{Name: "allow_domains", Type: field.TypeJSON, Nullable: true},
		{Name: "latest_visit_url", Type: field.TypeString, Nullable: true},
		{Name: "max_page", Type: field.TypeInt, Default: 1000},
	}
	// WebsitesTable holds the schema information for the "websites" table.
	WebsitesTable = &schema.Table{
		Name:       "websites",
		Columns:    WebsitesColumns,
		PrimaryKey: []*schema.Column{WebsitesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SellersTable,
		WebsitesTable,
	}
)

func init() {
}
