// Code generated by entc, DO NOT EDIT.

package seller

import (
	"time"
)

const (
	// Label holds the string label denoting the seller type in the database.
	Label = "seller"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTel holds the string denoting the tel field in the database.
	FieldTel = "tel"
	// FieldPrefecture holds the string denoting the prefecture field in the database.
	FieldPrefecture = "prefecture"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldOpenedAt holds the string denoting the opened_at field in the database.
	FieldOpenedAt = "opened_at"
	// FieldExported holds the string denoting the exported field in the database.
	FieldExported = "exported"
	// FieldExportedAt holds the string denoting the exported_at field in the database.
	FieldExportedAt = "exported_at"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// Table holds the table name of the seller in the database.
	Table = "sellers"
)

// Columns holds all SQL columns for seller fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldURL,
	FieldKey,
	FieldName,
	FieldTel,
	FieldPrefecture,
	FieldAddress,
	FieldLatitude,
	FieldLongitude,
	FieldOpenedAt,
	FieldExported,
	FieldExportedAt,
	FieldDisabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
