// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Seller is the predicate function for seller builders.
type Seller func(*sql.Selector)

// Website is the predicate function for website builders.
type Website func(*sql.Selector)
