// Code generated by entc, DO NOT EDIT.

package website

import (
	"time"
)

const (
	// Label holds the string label denoting the website type in the database.
	Label = "website"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldURLTemplate holds the string denoting the url_template field in the database.
	FieldURLTemplate = "url_template"
	// FieldAllowDomains holds the string denoting the allow_domains field in the database.
	FieldAllowDomains = "allow_domains"
	// FieldLatestVisitURL holds the string denoting the latest_visit_url field in the database.
	FieldLatestVisitURL = "latest_visit_url"
	// FieldMaxPage holds the string denoting the max_page field in the database.
	FieldMaxPage = "max_page"
	// Table holds the table name of the website in the database.
	Table = "websites"
)

// Columns holds all SQL columns for website fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKey,
	FieldURLTemplate,
	FieldAllowDomains,
	FieldLatestVisitURL,
	FieldMaxPage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMaxPage holds the default value on creation for the "max_page" field.
	DefaultMaxPage int
)
